Django/10-19/mysite2/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

Django/10-19/mysite2/tube/urls.py
from django.urls import path
from . import views

app_name = 'tube'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete', views.post_delete, name='post_delete'),
    path('<int:pk>/comment/new', views.comment_new, name='comment_new'),
]

Django/10-19/mysite2/tutorialdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tube/', include('tube.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='tube:post_list')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/10-19/mysite2/tube/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete = models.CASCADE
    )
    title = models.CharField(max_length=100)
    content = models.TextField()
    thumb_image = models.ImageField(
        upload_to = 'tube/images/%Y/%m/%d/' , blank=True
    )
    file_upload = models.FileField(
        upload_to = 'tube/files/%Y/%m/%d/', blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)
    tags = models.ManyToManyField('Tag', blank=True)
    
    def __str__(self):
        return self.title
    
    # 해당 객체의 절대 URL을 반환하는 함수입니다. 
    # URL은 '/tube/'와 해당 객체의 pk 값으로 구성됩니다.
    def get_absolute_url(self):
            return f'/tube/{self.pk}'  
    

class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    author = models.ForeignKey(
        Post, on_delete=models.CASCADE
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.message
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
# Create your models here.

Django/10-19/mysite2/tube/forms.py
from django import forms 
from .models import Post, Comment, Tag 

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'thumb_image', 'file_upload']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

Django/10-19/mysite2/accounts/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.urls import reverse_lazy

signup = CreateView.as_view(
    form_class = UserCreationForm,
    template_name = 'accounts/form.html',
    success_url = reverse_lazy('accounts:login')
)

login = LoginView.as_view(
    template_name = 'accounts/form.html',
)

logout = LogoutView.as_view(
    next_page = reverse_lazy('accounts:login')
)


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')
# Create your views here.

Django/10-19/mysite2/tube/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import models
# from django.db.models.query import QuerySet
from django.views.generic import ListView, DeleteView, UpdateView, DetailView, CreateView
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

class PostListView(ListView):
    model = Post
    # context_object_name = 'post_list' 기본세팅
    ordering = ['-pk']
    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', '')
        if q:
            qs = qs.filter(title__icontains=q)
        return qs
    
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('tube:post_list')
    template_name = 'tube/form.html'

    def form_valid(self, form):
        video = form.save(commit=False)
        video.author = self.request.user
        return super().form_valid(form)
    
class PostDetailView(DetailView):
    model = Post
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        post.view_count += 1
        post.save()
        return super().get_object(queryset)
    

class PostUpdateView(UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('tube:post_list')
    template_name = 'tube/form.html'
    
    def test_func(self):
        return self.get_object().author == self.request.user
    



class PostDeleteView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('tube:post_list')
    
    def test_func(self): # UserPassesTestMixin에 있고 test_func() 메서드를 오버라이딩, True, False 값으로 접근 제한
        return self.get_object().author == self.request.user


@login_required
def comment_new(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False) # commit=False는 DB에 저장하지 않고 객체만 반환
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('tube:post_detail', pk)
    else:
        form = CommentForm()
    return render(request, 'tube/form.html', {'form': form})

post_list = PostListView.as_view()
post_new = PostCreateView.as_view()
post_detail = PostDetailView.as_view()
post_edit = PostUpdateView.as_view()
post_delete = PostDeleteView.as_view()

Django/10-19/mysite2/templates/tube/form.html
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="글올리기" />
</form>

Django/10-19/mysite2/templates/tube/post_confirm_delete.html
<h1>글 삭제</h1>

<form action="" method="psot">
  {% csrf_token %}
  <p>글을 삭제하시겠습니까?</p>
  <input type="submit" value="네" class="btn btn-primary" />
</form>

Django/10-19/mysite2/templates/tube/post_detail.html
<h2>제목: {{ post.title }}</h2>
<p>작성자: {{ post.author }}</p>
<p>조회수: {{ post.view_count }}</p>
<p>{{ post.content }}</p>
<p><img src="{{ post.thumb_image.url }}" width="500px" alt="{{ post.thumb_image }}"></p>
{% if post.file_upload %}
<video src="{{ post.file_upload.url }}" controls width='500px'></video>
{% endif %}

<hr>

<section>
    <h3>댓글</h3>
    {% for comment in post.comments.all %}
    <p>{{ comment.message }}</p>
    <p>{{ comment.author }}</p>
    <p>{{ comment.updated_at }}</p>
    {% endfor %}
</section>
<section>
    <h3>댓글 작성</h3>
    <form action="{% url "tube:comment_new" post.pk %}" mothod='post'>
        {% csrf_token %}
        {{ comment.form.as_p }}
        <input type="submit" value='작성'>
    </form>
</section>

<a href="{% url "tube:post_list" %}">목록</a>
{% if user == post.author %}
<a href="{% url "tube:post_edit" post.pk %}">수정</a>
<a href="{% url "tube:post_delete" post.pk %}">삭제</a>
{% endif %}

Django/10-19/mysite2/templates/tube/post_list.html
<h1>포스트 목록</h1>

<form action="" method="GET">
  <input type="text" name="q" value="{{ request.GET.q }}" />
  <input type="submit" value="검색" />
</form>

<ul>
    {% for post in post_list %}
    <li>
        <a href="{% url "tube:post_detail" post.pk %}">{{ post.title }}</a>
        <p>{{ post.content }}</p>
    </li>
    {% endfor %}
</ul>

<a href="{% url "tube:post_new" %}">업로드</a>